config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root "static_pages#home"

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'

  resources :users, except: :new

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

	before_save {self.email = email.downcase}

	validates :name, presence: true,
					length: {maximum: 50}
	
	VALID_EMAIL_REGEX = /\A[\w\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :email, presence: true,
					length: {maximum: 250},
					format: { with: VALID_EMAIL_REGEX},
					uniqueness: {case_sensitive: false}

	validates :password, length: {minimum: 6}
	
	has_secure_password

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? 
			BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# returns a random token, e.g. "2q82-oKDQgv_-L17bquGcg"
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# remembers a user in the database for use in persistent sessions
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))		
	end

	#returns true if the provided token hashes out to match the
	# remember_digest stored in the database
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user   # helper method in sessions_helper
      params[:session][:remember_me] == '1' ? remember(user) :
          forget(user) # helper methods in sessions_helper
      redirect_to user
  	else
  		flash.now[:danger] = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user #in sessionshelper, available through include in applicationshelper
      #remember(@user) # in sessionshelper
      flash[:success] = "Welcome to Sample App"
  		redirect_to user_path(@user)
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  	#debugger if Rails.env.development?
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email,
  			:password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
#returns the full title on a per-page basis
	def full_title(page_title = '')
		title = "Rails Tutorial"
		title = page_title + " | " + title unless page_title.empty?
		title
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	# remembers a user in a permanent session as follows:
	# creates random characters as remember token, stores digest in database
	# stores encrypted user id in permanent cookie (20yr) in user's browser
	# stores unencrypted remember token as permanent cookie
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if (user_id = session[:user_id]) # assignment, not comparison
			@current_user ||= User.find_by(id: user_id)	
		elsif (user_id = cookies.signed[:user_id]) # permanently signed in
			#raise # this branch is not tested, so we don't get here
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	#forgets a persistent session by removing remember_token digest from database
	# and deleting permanent cookies
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		sz = options[:size]
		"https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{sz}"
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Ruby on Rails Tutorial
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", 'http://news.railstutorial.org' %></li>

		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<%= link_to "sample app", root_path, id: "logo" %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					
					<% if logged_in? %>
						<li><%= link_to "Users", "#" %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", "#" %></li>
								<li><%= link_to "Log out", logout_path, method: "delete" %></li>
							</ul>
						</li>

					<% else %>
						<%= link_to "Log in", login_path %></li>
					<% end %>
					
				</ul>
			</nav>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |type, msg| %>
			<%= content_tag(:div, msg, class:"alert alert-#{type}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger" >
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>About</h1>
<p>We live for Ruby on Rails.
</p>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact"%>
<h1>Contact us</h1>

app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1>Help for Sample App</h1>
<p>This is the home page for the <a href="www.railstutorials.org">Ruby on Rails Tutorial</a> sample application.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to Sample App</h1>
	<h2>This is the home page for the <a href="www.railstutorials.org">Ruby on Rails Tutorial</a> sample application.
	</h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
		'http://rubyonrails.org' %>

app/views/users/new.html.erb
<% provide :title, 'Sign up' %>
<h1>Sign up</h1>
<p>This will be a sign up page for new users.</p>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages' %>

			<%= f.label(:name) %>
			<%= f.text_field(:name, class: 'form-control') %>

			<%= f.label(:email) %>
			<%= f.email_field(:email, class: 'form-control') %>

			<%= f.label(:password) %>
			<%= f.password_field(:password, class: 'form-control') %>

			<%= f.label(:password_confirmation, "Confirm") %>
			<%= f.password_field(:password_confirmation, class: 'form-control') %>


			<%= f.submit "Create my account", class:"btn btn-primary" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user-info">
			<h1>
				<%= image_tag(gravatar_url(@user,{size: 200}) , alt: @user.name, class: "gravatar")%>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>


<%= @user.name %>, <%= @user.email %>